---
title: "Seed"
author: "Grupo_6"
format:
  html:
    toc: true
    toc-location: left
    number-sections: true
    self-contained: true
    output-file: "code"
editor_options: 
  chunk_output_type: console
execute: 
  echo: true
  message: false
  warning: false
---


# Setup

```{r}
#| label: setup

source("https://inkaverse.com/setup.r")

```

## Field-book


```{r}
url <- "https://docs.google.com/spreadsheets/d/1c7TJoo7CocyPumtJueQZEvETEQPnzLjwtTZBNp0sM8Q/edit?gid=2046240100#gid=2046240100"

gs <- url %>% 
  as_sheets_id()

fb <- gs %>% 
  range_read(ss = .,sheet = "fb")

```

```{r}
library(dplyr)
library(huito)
font <- c("Permanent Marker", "Tillana", "Courgette")

huito_fonts(font)
va <- 1.2

label <- fb %>%
  mutate(color = case_when(
    factor %in% "Con_Luz" ~ "blue"
    , factor %in% "Sin_Luz" ~ "red"
  )) %>%
  label_layout(size = c(5.2, 9.25), border_color = "forestgreen"
               , border_width = 1.5) %>%
  include_image(
    value = "logo.png",
    size = c(1.3, 1.3),
    position = c(0.8, 1.2),
    opts = "image_scale(200)"
  ) %>%
  include_barcode(
    value = "cod",
   , size = c(4.8, 4.8)
    , position = c(2.6, 5.5-va)
  ) %>%
  include_text(
    value = "GRUPO 6",
    , position = c(2.6, 2.1-va)
    ,size = 10,
    color = "brown",
    font = font[1]
  ) %>%
  include_text(
    value = "factor"
    , position = c(2.6, 2.5-va)
    , size = 16
    , color = "color" 
    , font = font[1]
  ) %>%
  include_text(
    value = "plots"
    , position = c(4.3, 9.5-va)
    , size = 16
    , color = "black"
    , font[1],
    font = font[1]
  ) %>% 
include_image(value = "https://huito.inkaverse.com/img/scale.pdf"
                , size = c(5, 1)
    , position = c(2.6, 8.5-va)
) %>% 
  include_image(value = "https://www.untrm.edu.pe/assets/images/untrmazul.png"
        , size = c(3, 3)
    , position = c(1.7, 9.5-va)
) %>% 
  include_image(value = "etiqueta/ing.jpg"
                , size = c(1.2, 1.3) 
                , position = c(4.5, 1.2)
)

label %>% 
  label_print(mode = "preview")
label %>%
  label_print(mode = "complete", filename = "Etiqueta_G6", nlabels = 12)

```

